apiVersion: apps/v1
kind: Rollout 
metadata:
  name: myweb
spec:
  replicas: 8
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - name: myweb
        image: pushdown99/myweb:latest
        ports:
        - containerPort: 3000
  strategy:
    canary:
      maxSurge: "25%"    
      maxUnavailable: 0  
      steps:
      - setWeight: 25    
      - pause: {}        

---
apiVersion: v1
kind: Service
metadata:
  name: myweb-service
spec:
  type: LoadBalancer
  selector:
    app: myweb
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000